### ISSUE TITLE
Avoid relying on package.json so any language can be supported

### ISSUE THREAD

**Issue by hawkins** [SaraVieira/fiddly#15]
Hey, awesome work with this! Looks like a super useful tool I know I could definitely use a ton.

One concern is that it seems to have some small reliance on package.json. I.e., GitHub corner pulls from the repository key in the package manifest.

**What would it take to have every configuration pulled from the fiddly’s own json file?** (It looks like almost everything does, but I’m on mobile and haven’t had a chance to take a look at the code myself to investigate this yet, sorry!)

That capability would be tremendous so we could use this project in conjunction with non-node projects, I.e. any project that does not have a package.json present

**Comment by hawkins** [comment]
This might already be done, but the projects readme makes it look like there might be just a teeny bit of work to be done to make it happen. So it might be a tiny bit of code, maybe just updating the readme, or a more serious amount of code. In any event, I’m happy to contribute to make it happen if this is a reasonable goal for the project. 🙂

**Comment by SaraVieira** [comment]
OH! This is great!

I think only the github repo and homepage comes from the package.json but can be easily moved to be able to be in both.


I can do this in 10m :)

**Comment by hawkins** [comment]
One thing I've noticed in this effort is that running without a `package.json` or `.fiddly.config.json` results in a message that seems like a success (your files have been made in the public folder, you can deploy that ...) but then prints a stack trace on an error when `fiddly.js:178` tries to access the first character of the `name`, which is undefined as we have obviously not specified a name in either the `package.json` or the `.fiddly.config.json` as both files do not exist.

So, if this issue is out-of-scope for the project, then we may want to at least add some warning messages here - i.e., "Fiddly could not determine the project's name - did you forget to make a .fiddly.config.json? See (URL) for more info" or something along those lines

**Comment by SaraVieira** [comment]
> fiddly.js:178 tries to access the first character of the name, which is undefined as we have obviously not specified a name in either the package.json or the .fiddly.config.json as both files do not exist.

This is actually fixed now, gonna publish with these changes too :)

**Comment by SaraVieira** [comment]
I believe a name should not be needed

**Comment by hawkins** [comment]
At least in what's published right now, not specifying a name does error out because:

```javascript
const name = options.name || packageJSON.name; // undefined

// line 178:
name.charAt(0) // error
```

**Comment by hawkins** [comment]
Fantastic though, beat me to my error PR too - thanks for all the speedy work!!! 🎉

**Comment by SaraVieira** [comment]
I defaulted in the latest version to an empty string:

```js
const title = name ? name.charAt(0).toUpperCase() + name.slice(1) : ''
```

I added all the changes in fiddly@0.7.3 can you try it out and see what happens?

**Comment by SaraVieira** [comment]
That issue was actually found when making more tests so yaay for tests

**Comment by hawkins** [comment]
Yep, I was on 0.7.2 installed just before you pushed :) Nice! 0.7.3 fixed that issue, thanks!

Does 0.7.3 include support for pulling every bit of config from the fiddly file now than too?

**Comment by SaraVieira** [comment]
> Does 0.7.3 include support for pulling every bit of config from the fiddly file now than too?

Yes! :D

**Comment by SaraVieira** [comment]
There is now the "repo" option in the .fiddly.config

**Comment by hawkins** [comment]
That's just fantastic!! 🎉 Thanks so much, Sara! I guess that's everything for this issue then!

**Comment by SaraVieira** [comment]
YAAAY! Let me know if you use because I wanna later put a list of repo's using it :D

**Comment by hawkins** [comment]
I definitely will, probably a ton quite frankly haha. I'll keep you posted! 👍
