### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by hawkins** [SaraVieira/fiddly#16]
Not sure what I'm doing wrong, but the following image that shows up on GitHub does not get copied into the public folder and is thus not found when deployed:

```markdown
 ![Screenshot of Lard 0.0.0 folder view for 'Coding'](screenshots/folder.png)
```

For reference, I'm testing using https://github.com/hawkins/lard 's master repo as a "no-config" test since it has no .fiddly.config or package.json

**Comment by hawkins** [comment]
The `<img>` tag is included, however, so I'm fairly positive this is user error 😅  https://public-vmbngwkvmw.now.sh

**Comment by SaraVieira** [comment]
Soooo I figured out the issue:

The filsystem doesn't recognize this as path:

```
screenshots/folder.png
```

so you need to make it like so and it works well

```
![Screenshot of Lard 0.0.0 folder view for 'Coding'](./screenshots/folder.png)
```


I am actually kind of amazed that worked on Github 🤔

**Comment by SaraVieira** [comment]
<img width="1552" alt="screenshot 2018-12-28 at 20 10 12" src="https://user-images.githubusercontent.com/1051509/50526849-99260780-0adc-11e9-8a08-fd5909bb4c21.png">

**Comment by hawkins** [comment]
I just caught that myself as well, had literally typed a message to close this and everything. You're a ninja! Thanks so much.

**Comment by SaraVieira** [comment]
https://media1.giphy.com/media/EPaebv5YaeqWs/giphy.gif?cid=3640f6095c2683ad6c484b642ee85df1


NINIJA CAT
