### ISSUE TITLE
Does not run via npx or as dependency

### ISSUE THREAD

**Issue by gnapse** [SaraVieira/fiddly#3]
I tried running it for [jest-dom](https://github.com/gnapse/jest-dom) via `npx` and I got this

```
$ npx fiddly
npm ERR! path /Users/ernesto/.npm/_npx/68510/lib/node_modules/fiddly/bin/fiddly
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/ernesto/.npm/_npx/68510/lib/node_modules/fiddly/bin/fiddly'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Tried with node v10.2.1 and v8.11.3. Both gave the same result.

### Installing it as dependency

Then I tried installing it as a dependency, as documented in the README, but got this:

```
$ npm install --save-dev fiddly
npm ERR! path /Users/ernesto/code/oss/jest-dom/node_modules/fiddly/bin/fiddly
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/ernesto/code/oss/jest-dom/node_modules/fiddly/bin/fiddly'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ernesto/.npm/_logs/2018-12-26T12_48_16_179Z-debug.log
```

There must be something wrong with my env, because I doubt this would fail so blatantly out of the box given the straightforward instructions, but I'm not sure what it could be.

**Comment by SaraVieira** [comment]
🤦‍♀️

So what happened is that I made the bin a js file but didn't change it in the package.json :(

It's now fixed in version 0.3

https://github.com/SaraVieira/fiddly/releases/tag/v0.3.0

Sorry

**Comment by SaraVieira** [comment]
It should look something like this in dark: https://5c2381e1724ef9d69ec7827f--fiddly.netlify.com/

**Comment by gnapse** [comment]
Nice, thanks!
