### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by fleaz** [SaraVieira/fiddly#31]
Hey,

any chance we can get a new release with bumped up dependencies? There are currently 5  vulnerabilities (4 high and 1 low) in the dependencies of fiddly.

Best,
Felix

**Comment by SaraVieira** [comment]
Hey!

Sure! Give me 20m :)

Its not that's abandoned, I just had notifications on github turned off for a long time :(

**Comment by SaraVieira** [comment]
Hey!

All packages have been updated in version 0.9.0
https://github.com/SaraVieira/fiddly/releases/tag/v0.9.0

**Comment by fleaz** [comment]
AWESOME! :tada: 
Thanks a lot :)
