### ISSUE TITLE
No focus style for links in light theme

### ISSUE THREAD

**Issue by sapegin** [SaraVieira/fiddly#5]
This makes the page inaccessible using a keyboard.

<img width="1358" alt="image 2018-12-26 at 3 30 46 pm" src="https://user-images.githubusercontent.com/70067/50448753-3a695e00-0923-11e9-8409-35e743fd0764.png">

**Comment by SaraVieira** [comment]
It was a problem on both :(

There was an outline none hidden in https://yegor256.github.io/tacit/, I'm gonna create a PR for it and time being updated it here
