### ISSUE TITLE
TypeError: Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by cktang88** [SaraVieira/fiddly#6]
Running on https://github.com/VandyHacks/vaken gives the following:

![image](https://user-images.githubusercontent.com/10319942/50453375-ca001400-0905-11e9-90d2-9f41238e22db.png)

**Comment by SaraVieira** [comment]
Hey !

Thanks for saying the repo! It is now fixed, it was an issue with images :(

You can try again and let me know if you find any issues
